---
- hosts: node
  remote_user: root


  tasks:
    - name: Installing Apache
      yum:
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Install MySQL
      yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm  state=present

    - name: Install MYSQL
      yum: pkg={{ item }}
      with_items:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python

    - name: Start the MySql service
      service:
        name: mysqld
        enabled: yes
        state: started


    - name: Installing PHP
      yum:
        name:
          - php
          - php-mysql
        state: latest

    - name: Copying your php file in the /var/www/html
      copy:
        src: /root/ansibleplaybook/index.php
        dest: /var/www/html/index.php
